#!/bin/sh
################################################################################
#  Copyright 2010-2011 CloudBees Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
################################################################################
set +e
set -x

. ./lib/build.sh

thrift_name=thrift-$version-$(addon_architecture)
platform=$(addon_platform)

is_built=$(addon_is_built thrift/${platform}/${thrift_name}.tar.bz2)

if [ $is_built == "1" ]; then
    echo "$thrift_name.tar.bz2 is already compiled and deployed"
    exit 0
else
    set -e

    addon_clean_build
    cd build

    # Download
    wget http://archive.apache.org/dist/thrift/${version}/thrift-${version}.tar.gz

    # Unpack
    tar xzf thrift-${version}.tar.gz

    # Build
    cd thrift-${version}

    export JAVA_PREFIX=/scratch/jenkins/thrift/${thrift_name}/java
    export PY_PREFIX=/scratch/jenkins/thrift/${thrift_name}/python
    export RUBY_PREFIX=/scratch/jenkins/thrift/${thrift_name}/ruby
    export PERL_PREFIX=/scratch/jenkins/thrift/${thrift_name}/perl

    #export ERLANG_INSTALL_LIB_DIR=/scratch/jenkins/thrift/${thrift_name}/erlang
    #export PHP_PREFIX=/scratch/jenkins/thrift/${thrift_name}/php

    ./configure --prefix=/scratch/jenkins/thrift/${thrift_name} --with-erlang=no --with-php=no
    make && make install ; true
    make install

    # Package
    addon_package "/scratch/jenkins/thrift/${thrift_name}"

    #Publish
    addon_publish "thrift/${platform}/${thrift_name}.tar.bz2" "${thrift_name}.tar.bz2"
fi
