#!/bin/sh
################################################################################
#  Copyright 2012 CloudBees Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
################################################################################
set -eu
wget -q https://repository-cloudbees.forge.cloudbees.com/distributions/ci-addons/thrift/use-thrift
THRIFT_VERSION=${version} . ./use-thrift
thrift -help
thrift -version

simpleversion=$(echo $version | sed s/-//g)
echo "Looking for ${simpleversion}"
regex="thrift *${simpleversion}*"
echo "Looking using ${regex}"
output=$(thrift -version)
echo "Checking against ${output}"
if [[ $output == $regex ]]; then
  echo Match: $output
else
  echo No match: $output
  exit 1
fi
