#!/bin/sh
################################################################################
#  Copyright 2010-2011 CloudBees Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
################################################################################
set +e

. ./lib/build.sh

unset GEM_PATH
unset GEM_HOME
unset BUNDLE_PATH

ruby_name=ruby-$version-$(addon_architecture)
platform=$(addon_platform)

is_built=$(addon_is_built ruby/${platform}/${ruby_name}.tar.bz2)

if [ $is_built == "1" ]; then
    set -e
    echo "$ruby_name.tar.bz2 is already compiled and deployed"
else
    set -e

    ruby_versions=("1.8.7-p370")
    for i in ${ruby_versions[@]}; do
      echo Patching: ${i}
      echo     File: ruby-build/share/ruby-build/$i
      curl https://gist.github.com/gists/4166844/download >> ../ruby-build/share/ruby-build/$i
    done

    addon_clean_build
    cd build

    CONFIGURE_OPTS="--with-openssl-dir=/usr \
                   --with-out-ext=readline \
                  --with-zlib-dir=/usr \
                   --disable-option-checking"

    # Some of the older Ruby versions require an old OpenSSL
    openssl_versions=("ree-1.8.6-2009.06" "1.8.6-p240" "1.8.6-p383" "1.8.6-p420" "1.8.7-p249" "1.9.1-p378")
    for i in ${openssl_versions[@]}; do
      OPENSSL=openssl-0.9.8t
      if [ "$i" = "$version" ]; then
        test -f ${OPENSSL}.tar.gz || wget http://www.openssl.org/source/${OPENSSL}.tar.gz
        test -d ${OPENSSL} || tar xzf ${OPENSSL}.tar.gz
        CONFIGURE_OPTS="--with-openssl-dir=`pwd`/${OPENSSL} \
	              --with-out-ext=readline \
                       --with-zlib-dir=/usr \
                       --disable-option-checking"
      fi
    done


    CONFIGURE_OPTS="${CONFIGURE_OPTS:-} --enable-load-relative" \
      TMPDIR=$(pwd) \
      ruby-build $version /scratch/jenkins/ruby/$ruby_name


    addon_package "/scratch/jenkins/ruby/${ruby_name}"

    addon_publish "ruby/${platform}/${ruby_name}.tar.bz2" "${ruby_name}.tar.bz2"
fi
