#!/bin/sh
################################################################################
#  Copyright 2010-2011 CloudBees Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
################################################################################
# To call this script:
# wget -q https://repository-cloudbees.forge.cloudbees.com/distributions/ci-addons/ruby/use-ruby
# RUBY_VERSION=1.8.7-p352 . ./use-ruby

if [[ -z $RUBY_VERSION ]]; then
   echo "You must set the RUBY_VERSION environment variable. See http://wiki.cloudbees.com/bin/view/DEV/Ruby+Builds" 1>&2
fi

ruby187="1.8.7-*"
if [[ $RUBY_VERSION == $ruby187 ]]; then
  echo "Ruby 1.8.7 has difficulties compiling on modern operating systems due to compiler changes."
  echo "As a result we have disabled these versions."
  echo "Please contact support if you have a dire need for them."
  exit 1
fi

# Grab our library file
if [ ! -f /scratch/jenkins/use.sh ]; then
  wget -q -P /scratch/jenkins https://repository-cloudbees.forge.cloudbees.com/distributions/ci-addons/lib/use.sh
fi
. /scratch/jenkins/use.sh


mkdir -p /scratch/jenkins/ruby

ruby_name=ruby-${RUBY_VERSION}-$(addon_architecture)

if [ ! -f /scratch/jenkins/ruby/${ruby_name}.tar.bz2 ]; then
  wget -q -P /scratch/jenkins/ruby \
             https://repository-cloudbees.forge.cloudbees.com/distributions/ci-addons/ruby/$(addon_platform)/${ruby_name}.tar.bz2
fi

if [ ! -f /scratch/jenkins/ruby/${ruby_name}/bin/ruby ]; then
  tar xjf /scratch/jenkins/ruby/${ruby_name}.tar.bz2 -C /scratch/jenkins/ruby
fi


export PATH=/scratch/jenkins/ruby/${ruby_name}/bin:$PATH

unset GEM_PATH
unset GEM_HOME
unset BUNDLE_PATH
