#!/bin/sh
################################################################################
#  Copyright 2010-2011 CloudBees Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
################################################################################
set +e

. ./lib/build.sh

php_name=php-$version-$(addon_architecture)

is_built=$(addon_is_built php/${php_name}.tar.bz2)

if [ $is_built == "1" ]; then
    echo "$php_name.tar.bz2 is already compiled and deployed"
    exit 0
else
    set -e

    addon_clean_build
    cd build

    # Download
    regex='.*(RC|alpha|beta).*'
    if [[ $version =~ $regex ]]; then
        wget http://downloads.php.net/dsp/php-${version}.tar.bz2
    else
        wget http://us3.php.net/distributions/php-${version}.tar.bz2
    fi

    # Unpack
    tar xjf php-${version}.tar.bz2

    # Build
    cd php-${version}
    ./configure --prefix=/scratch/jenkins/php/${php_name} \
        --with-curl
    make && make install

    # Package
    addon_package "/scratch/jenkins/php/${php_name}"

    #Publish
    addon_publish php/${php_name}.tar.bz2 ${php_name}.tar.bz2
fi
