#!/bin/sh
################################################################################
#  Copyright 2010-2011 CloudBees Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
################################################################################
# To call this script:
#  wget -q https://repository-cloudbees.forge.cloudbees.com/distributions/ci-addons/php/use-php
#  PHP_VERSION=5.4.8 . use-php

if [[ -z $PHP_VERSION ]]; then
   echo "You must set the PHP_VERSION environment variable. See http://wiki.cloudbees.com/bin/view/DEV/PHP" 1>&2
fi

mkdir -p /scratch/jenkins/php
ARCH=`uname -m`

php_name=php-${PHP_VERSION}-${ARCH} #$(uname -p)

if [ ! -f /scratch/jenkins/php/${php_name}.tar.bz2 ]; then
  wget -q -P /scratch/jenkins/php \
             https://repository-cloudbees.forge.cloudbees.com/distributions/ci-addons/php/${php_name}.tar.bz2
fi

cd /scratch/jenkins/php
if [ ! -f /scratch/jenkins/php/${php_name}/bin/php ]; then
  tar xjf /scratch/jenkins/php/${php_name}.tar.bz2
fi

export PATH=/scratch/jenkins/php/${php_name}/bin:$PATH
