#!/bin/sh
################################################################################
#  Copyright 2010-2011 CloudBees Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
################################################################################
# To call this script:
#  wget -q https://repository-cloudbees.forge.cloudbees.com/distributions/ci-addons/php/use-php
#  PHP_VERSION=5.4.13 . use-php

set -eu

if [[ -z $PHP_VERSION ]]; then
   echo "You must set the PHP_VERSION environment variable. See http://wiki.cloudbees.com/bin/view/DEV/PHP" 1>&2
   exit 1
fi

# Grab our library file
if [ ! -f /scratch/jenkins/use.sh ]; then
  wget -q -P /scratch/jenkins https://repository-cloudbees.forge.cloudbees.com/distributions/ci-addons/lib/use.sh
fi
. /scratch/jenkins/use.sh

php_name=php-${PHP_VERSION}-$(addon_architecture) #$(uname -p)

addon_download "php" "${php_name}"

addon_extract "php" "${php_name}" "bin/php"

export PATH=/scratch/jenkins/php/${php_name}/bin:$PATH
