#!/bin/sh
################################################################################
#  Copyright 2012 CloudBees Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
################################################################################

set -eu
wget -q https://repository-cloudbees.forge.cloudbees.com/distributions/ci-addons/python/use-python
PYTHON_VERSION=${version} . ./use-python

regex="3.*"
if [[ $version == $regex ]]; then
  echo calling python3 -V
  output=$(python3 -V 2>&1)
else
  echo calling python -V
  output=$(python -V 2>&1)
fi

regex="Python ${version}"
if [[ $output == $regex ]]; then
  echo Match: $output [looking for $regex]
  exit 0
else
  echo No match: $output [looking for $regex]
  exit 1
fi
