#!/bin/sh
################################################################################
#  Copyright 2010-2011 CloudBees Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
################################################################################
# To call this script:
# wget -q https://repository-cloudbees.forge.cloudbees.com/distributions/ci-addons/python/use-python
# PYTHON_VERSION=2.7.2 . ./use-python

if [[ -z $PYTHON_VERSION ]]; then
   echo "You must set the PYTHON_VERSION environment variable. See http://wiki.cloudbees.com/bin/view/DEV/Python+Builds" 1>&2
fi

mkdir -p /scratch/jenkins/python
ARCH=`uname -m`

python_name=python-${PYTHON_VERSION}-${ARCH} #$(uname -p)

if [ ! -f /scratch/jenkins/python/${python_name}.tar.bz2 ]; then
  wget -q -P /scratch/jenkins/python \
    https://repository-cloudbees.forge.cloudbees.com/distributions/ci-addons/python/${python_name}.tar.bz2
fi

# python changes names per major version, so look for pip
if [ ! -f /scratch/jenkins/python/${python_name}/bin/pip ]; then
  tar xjf /scratch/jenkins/python/${python_name}.tar.bz2 -C /scratch/jenkins/python
fi

export PYTHON_HOME=/scratch/jenkins/python/${python_name}
export PATH=$PYTHON_HOME/bin:$PATH
