#!/bin/sh
################################################################################
#  Copyright 2010-2011 CloudBees Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
################################################################################
# To call this script:
# wget -q https://repository-cloudbees.forge.cloudbees.com/distributions/ci-addons/python/use-python
# PYTHON_VERSION=2.7.2 . ./use-python

if [[ -z $PYTHON_VERSION ]]; then
   echo "You must set the PYTHON_VERSION environment variable. See http://wiki.cloudbees.com/bin/view/DEV/Python+Builds" 1>&2
fi

# Grab our library file
if [ ! -f /scratch/jenkins/use.sh ]; then
  wget -q -P /scratch/jenkins https://repository-cloudbees.forge.cloudbees.com/distributions/ci-addons/lib/use.sh
fi
. /scratch/jenkins/use.sh

# Ideally this should go in an addons subdirectory, but this would probably break client scripts
BASE=/scratch/jenkins
mkdir -p ${BASE}

python_name=python-${PYTHON_VERSION}-$(addon_architecture)

if [ ! -f ${BASE}/python/${python_name}.tar.bz2 ]; then
  wget -q -P ${BASE}/python \
    https://repository-cloudbees.forge.cloudbees.com/distributions/ci-addons/python/$(addon_platform)/${python_name}.tar.bz2
fi

# python changes names per major version, so look for pip
if [ ! -f ${BASE}/python/${python_name}/bin/pip ]; then
  tar xjf ${BASE}/python/${python_name}.tar.bz2 -C ${BASE}/python
fi

export PYTHON_HOME=${BASE}/python/${python_name}
export PATH=${PYTHON_HOME}/bin:$PATH
