#!/bin/sh
################################################################################
#  Copyright 2010-2011 CloudBees Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
################################################################################
set +e

. ./lib/build.sh

postgresql_name=postgresql-$version-$(addon_architecture)

is_built=$(addon_is_built postgresql/fc17/${postgresql_name}.tar.bz2)

if [ $is_built == "1" ]; then
    echo "$postgresql_name.tar.bz2 is already compiled and deployed"
    exit 0
else
    set -e

    addon_clean_build
    cd build

    # Download
    wget --continue http://ftp.postgresql.org/pub/source/v${version}/postgresql-${version}.tar.bz2

    # Unpack
    tar xjf postgresql-${version}.tar.bz2

    # Build
    mkdir -p /scratch/jenkins/postgresql/${postgresql_name}
    cd postgresql-${version}
    ./configure --prefix=/scratch/jenkins/postgresql/${postgresql_name}  --without-readline
    make && make install
    # Required for contrib package DBLink
    make -C src/backend ../../src/include/utils/fmgroids.h
    make -C contrib && make -C contrib install

    # Package
    addon_package "/scratch/jenkins/postgresql/${postgresql_name}"

    #Public
    addon_publish postgresql/fc17/${postgresql_name}.tar.bz2 ${postgresql_name}.tar.bz2
fi



