#!/bin/sh
################################################################################
#  Copyright 2010-2011 CloudBees Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
################################################################################

set -eu

# For some reason Jenkins is not clearing this area between some builds
set +e
killall postmaster
set -e
rm -rf /tmp/postgresql-data

wget -q https://repository-cloudbees.forge.cloudbees.com/distributions/ci-addons/postgresql/use-postgresql
POSTGRESQL_VERSION=${version} . ./use-postgresql

regex="psql *${version}*"
output=$(psql -V)
if [[ $output == $regex ]]; then
  echo Match: $output
else
  echo No match: $output
  exit 1
fi

cat /tmp/postgresql-data/postgres.log
# For tracing errors:
ps auxww
psql -c "SELECT * FROM PG_DATABASE;" template1 $USER

pg_ctl -D ${PGDATA} -m fast stop
