#!/bin/sh
################################################################################
#  Copyright 2010-2011 CloudBees Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
################################################################################

. ./lib/build.sh

node_name=node-$version-$(addon_architecture)

is_built=$(addon_is_built node/${node_name}.tar.bz2)

if [ $is_built == "1" ]; then
    echo "$node_name.tar.bz2 is already compiled and deployed"
    exit 0
else
  set -e
  NODEDIR=$WORKSPACE/../node-src
  mkdir -p $NODEDIR
  cd $NODEDIR

  NODE_URL=http://nodejs.org/dist/v${version}/node-v${version}.tar.gz
  echo Downloading ${NODE_URL}
  wget -q $NODE_URL

  tar xf node-v${version}.tar.gz


  # Build
  cd node-v${version}
  INSTALL_DIR=/scratch/jenkins/addons/node/${node_name}
  npm_config_prefix=$INSTALL_DIR
  # The --without-snapshot is required to build 0.7 series on the GCC 4.7-pre build we have on FC
  ./configure --prefix=${npm_config_prefix} --without-snapshot
  make
  make install

  export PATH=$INSTALL_DIR/bin:$PATH

  curl https://npmjs.org/install.sh | clean=yes sh

  addon_package "/scratch/jenkins/node/${node_name}"

  #Publish
  addon_publish node/${node_name}.tar.bz2 ${node_name}.tar.bz2
fi
