#!/bin/sh
################################################################################
#  Copyright 2010-2011 CloudBees Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
################################################################################
# To call this script:
# wget -q https://repository-cloudbees.forge.cloudbees.com/distributions/ci-addons/node/use-node
# NODE_VERSION=0.7.8 . ./use-node
if [[ -z $NODE_VERSION ]]; then
   echo "You must set the NODE_VERSION environment variable. See http://wiki.cloudbees.com/bin/view/DEV/Node+Builds" 1>&2
   exit 1
fi

set -eu

# Grab our library file
if [ ! -f /scratch/jenkins/use.sh ]; then
  wget -q -P /scratch/jenkins https://repository-cloudbees.forge.cloudbees.com/distributions/ci-addons/lib/use.sh
fi
. /scratch/jenkins/use.sh

ARCH=$(addon_architecture)
node_name=node-${NODE_VERSION}-${ARCH}

addon_download "node" "${node_name}"
# The addons/ prefix is due to legacy scripts potentially expecting it in a subdirectory
# We may be able to fix this at some point
addon_extract  "addons/node" "${node_name}" "bin/node"

export PATH=/scratch/jenkins/addons/node/${node_name}/bin:$PATH
