#!/bin/sh
################################################################################
#  Copyright 2010-2011 CloudBees Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
################################################################################
# To call this script:
#  wget -q https://repository-cloudbees.forge.cloudbees.com/distributions/ci-addons/redis/use-redis
#  REDIS_VERSION=2.6.4 . use-redis

if [[ -z $REDIS_VERSION ]]; then
   echo "You must set the REDIS_VERSION environment variable. See http://wiki.cloudbees.com/bin/view/DEV/Redis+Builds" 1>&2
fi

mkdir -p /scratch/jenkins/redis
ARCH=`uname -m`

redis_name=redis-${REDIS_VERSION}-${ARCH} #$(uname -p)

if [ ! -f /scratch/jenkins/redis/${redis_name}.tar.bz2 ]; then
  wget -q -P /scratch/jenkins/redis \
             https://repository-cloudbees.forge.cloudbees.com/distributions/ci-addons/redis/${redis_name}.tar.bz2
fi

cd /scratch/jenkins/redis
if [ ! -f /scratch/jenkins/redis/${redis_name}/bin/redis-server ]; then
  tar xjf /scratch/jenkins/redis/${redis_name}.tar.bz2
fi

export PATH=/scratch/jenkins/redis/${redis_name}/bin:$PATH
